// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'C:/Users/grant.fan/Code/React/React-Ant/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import TableOutlined from 'C:/Users/grant.fan/Code/React/React-Ant/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, TableOutlined };
